# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daily',
            options={'managed': False, 'ordering': ('-create_date',)},
        ),
    ]
